dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: 5.0/stable
sudo: required
language: csharp
mono: none
script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet build
  - dotnet test